### ISSUE TITLE
Flex item and min-width 0

### ISSUE THREAD

**Issue by rafaelchiti** [byronmwong/react-flexbox-layout#18]
I've found this issue a few times already where having a flex item that has inside a long word without spaces will cause the text to overflow, explanation:
https://groups.google.com/forum/#!topic/mozilla.dev.platform/0ZmJwayNsCY

Issue: https://jsfiddle.net/cLxdjuLn/

Wondering if you @byronmwong know something about this? Im not sure I fully understand this but ended up putting already 3 min-widths in my code for fixing, wondering if that makes sense or if it should be part of the library? maybe you are more familiar already with this issue.

Thanks!

**Comment by bywo** [comment]
Haven't encountered this issue yet, but glad there's a decent workaround
for it. I'm not sure if we should wrap everything in `min-width: 0`; not
sure if it'd break other layouts.

**Comment by rafaelchiti** [comment]
okok, will take a look then and see we bump into another scenario, wanted to ask first because maybe you already knew about it. Feel free to close the ticket

**Comment by bywo** [comment]
👍 lemme know if you find out anything more!
