### ISSUE TITLE
IE 10 & 11 flex basis incompatability

### ISSUE THREAD

**Issue by AaronLasseigne** [byronmwong/react-flexbox-layout#19]
In the CSS the `flex` definitions contain no units when the basis is "0". This breaks in IE 10 & 11. The recommendation is to use `%` to force a unit that is unlikely to be stripped away by CSS minifiers.

https://github.com/philipwalton/flexbugs#4-flex-shorthand-declarations-with-unitless-flex-basis-values-are-ignored

**Comment by bywo** [comment]
thanks for pointing this out! I made a branch called `fixIE`; do you mind pulling that and testing that with your layouts?

**Comment by AaronLasseigne** [comment]
Nope. I believe the problem is also related to the inline styles generated here: https://github.com/byronmwong/react-flexbox-layout/blob/fixIE/src/horizontal_item.jsx#L38

**Comment by bywo** [comment]
@AaronLasseigne luckily the helper you mentioned uses individual flex properties (`flex-grow`, `flex-shrink`, `flex-basis`) instead of the shorthand, so I think we're good there.

Let me know if your layouts are working in IE 10/11 😃

**Comment by AaronLasseigne** [comment]
They are not.

**Comment by AaronLasseigne** [comment]
Hmm, when I first tested this it didn't work. I think our build pipeline might have had something to do with that. 😦

It looks good now. 👍

**Comment by bywo** [comment]
great to hear!

resolved in `1.2.1`
