### ISSUE TITLE
Does lodash really need to be a peer dependency?

### ISSUE THREAD

**Issue by holden-caulfield** [byronmwong/react-flexbox-layout#20]
I'm using react-flexbox-layout on a project on which I'm not using lodash.
NPM is giving me the usual warning about peer dependencies.

I wonder if lodash shouldn't just be a project dependency only and get removed of peer dependencies on package.json

**Comment by bywo** [comment]
@holden-caulfield I think you're right.

As a quick fix to unblock you, you can manually install lodash in your project. I'll work on moving `lodash` to `dependencies`!

**Comment by holden-caulfield** [comment]
Thanks for the quick response! I went with the quick fix, just noticed you already merged the actual fix together with some really cool stuff (moving to lodash 4 and making it include only the needed fragments on the build). So will eventually grab the next release and use it!

**Comment by bywo** [comment]
resolved in `1.2.1`

**Comment by jonaskello** [comment]
+1 For removing lodash. IMHO lodash is great for applications but not for small libs. In this case I would say the issues it causes when importing the lib (eg. compability, size) outweighs the problems it solves for implementing the the lib (a few utility methods that could easily be replicated in an internal utils file). This is just my opinion though, I guess one could argue keeping it too. :-)
