### ISSUE TITLE
Any reason for not being compatible with React 15.1.x?

### ISSUE THREAD

**Issue by holden-caulfield** [byronmwong/react-flexbox-layout#25]
With latest react 15.1.0 available, had to force react on my project to stick to 15.0.1 because of the fixed dependency to 15.0.x on react-flexbox layout.

Wondering if there was any reason for react-flexbox-layout not to support the latest. 

Forked the repo and gave it a quick try moving versions to ^15.0.1: https://github.com/byronmwong/react-flexbox-layout/compare/master...holden-caulfield:master

Tests seems to run well but not sure if that is enough. Happy to create a PR for that change, but thought about asking first if there was a bigger reason not to do this.

Thanks!

**Comment by bywo** [comment]
No reason to be stuck with 15.0.x. It just didn't cross my mind. The codebase I'm working on is still 13.x actually! 😞 

A PR would be great! Thanks

**Comment by holden-caulfield** [comment]
Done! https://github.com/byronmwong/react-flexbox-layout/pull/26

**Comment by bywo** [comment]
published as `1.2.3`
